[package]
name = "crosswords-be"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rust-s3 = "0.32.3"
actix-web = "4"
env_logger = "0.10.0"
log = "0.4.17"
