name: Fly Deploy
on:
  push:
    branches:
      - 'main'
env:
#   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
#   deploy:
#       name: Deploy app
#       runs-on: ubuntu-latest
#       needs: clippy_check
#       steps:
#         - uses: actions/checkout@v2
#         - uses: superfly/flyctl-actions/setup-flyctl@master
#         - run: flyctl deploy --remote-only
